spring.application.name=eureka-server
server.port=8761

# By default Eureka tries to register ITSELF as a client.
# Since this IS the server, we turn that off.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false